- name: Install Express Generator
  npm:
    name: express-generator
    global: yes

- name: Create express Demo Project
  shell: rm -rf www.example.com; express www.example.com
  args:
    chdir: /data/wwwroot/

- name: Install Demo Project module
  shell: |
    npm install 
    pm2 start bin/www
    pm2 save
    pm2 startup
  args:
    chdir: /data/wwwroot/www.example.com

- name: Start pm2 
  service:
    name: pm2-root
    state: restarted
    enabled: yes
